apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: load-test
build:
  artifacts:
    - image: service-a
      docker:
        dockerfile: Dockerfile
      context: service-a
manifests:
  rawYaml:
    - k8s/service-a.yaml
    - k8s/service-b.yaml
    - k8s/scaled-object.yaml
    - k8s/ingress.yaml
# TODO jib, python( install uv/ruff), rust, go
# deploy:  -> helm
