apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: load-test
build:
  artifacts:
    - image: service-a
      jib:
        type: gradle
      context: service-a
    - image: service-b
      jib:
        type: gradle
      context: service-b
manifests:
  rawYaml:
    - k8s/service-a.yaml
    - k8s/service-b.yaml
    - k8s/scaled-object.yaml
    - k8s/ingress.yaml
# TODO jib, python( install uv/ruff), rust, go
# Config reload -> with spring config/config maps
# CI/CD
# deploy:  -> helm
