apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: load-test
build:
  artifacts:
    - image: loadtest
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/spring-boot-service.yaml
    - k8s/scaled-object.yaml
    - k8s/ingress.yaml
# TODO jib, python( install uv/ruff), rust, go