apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: load-test
build:
  artifacts:
    - image: loadtest
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
    - spring-boot-service.yaml
#    - HPA.yaml
