apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaled
spec:
  scaleTargetRef:
    name: service-d # (1)
  cooldownPeriod: 10 # (2)
  minReplicaCount: 0 # (3)
  maxReplicaCount: 3 # (3)
  advanced:
    horizontalPodAutoscalerConfig: # (4)
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
  triggers: # (5)
    - type: kafka
      metadata:
        bootstrapServers: host.minikube.internal:9092
        consumerGroup: a
        topic: test-topic
        lagThreshold: '5'